### ISSUE TITLE
Press `space` to open the first http(s) reference in browser

### ISSUE THREAD

**Issue by mertssmnoglu** [orhun/flawz#11]
**Is your feature request related to a problem? Please describe.**

I wanted to open the reference links of a random CVE and tried to clicking the urls with `ctrl + click` but it doesn't open anything. I need to write the whoole url to my web browser manually.

**Describe the solution you'd like**

Pressing space button can trigger `xdg-open HTTP_URL`, `open HTTP_URL` or something like that.

**Describe alternatives you've considered**

Surfing around the references with `j,k` or `up,down` keys and opening them in Web Browser via `space`

**Additional context**

The details page that I talking about.
![20240518_23h31m07s_grim](https://github.com/orhun/flawz/assets/61623638/d48e7eff-4f5e-44db-8610-5bb027661ddb)

There is also `ftp://` urls too, thats why I highlighted http(s) in the feature request.

**Comment by orhun** [comment]
It's a good idea! Are you interested in contributing?

**Comment by mertssmnoglu** [comment]
> It's a good idea! Are you interested in contributing?

Yes, I'm into the contributing. I don't actively coding with Rust, but I will try to implement this feature in [my fork](https://github.com/mertssmnoglu/fork_flawz).
