### ISSUE TITLE
Premature search closing

### ISSUE THREAD

**Issue by steven-beard** [orhun/flawz#66]
Describe the bug

The search unexpectedly closes whenever I search for any term that contains the letter 'q'. 

To reproduce

    Build with the default arguments.
    Run the application.
    Attempt to search for any term containing the letter 'q' (e.g., "quick", "question").
    Observe the search closing unexpectedly.

Expected behavior

I expected the application to return search results without closing, regardless of whether the search term contains a 'q'.

Screenshots / Logs

I don't have screenshots, but the search closes without any error logs or messages displayed.

Software information

    Operating system: 6.11.2-arch-1
    Rust version: rustc 1.81.0
    Project version: 0.2.2

Additional context

This issue seems to occur consistently whenever a 'q' is included in the search term. No other characters seem to trigger the same behavior.

**Comment by orhun** [comment]
Thanks, this should be now fixed in `main` :) Creating a new release shortly.
